'use client'

import { useMemo, useState } from 'react'
import IssrApp from '@/components/issr-app'
import { createClient } from '@/lib/supabase/client'

type EntrySummary={travel_date:string;distance_km:number;total_amount:number;rep_bonus:number;rep_plus_bonus:number}
type Establishment={id:string;name:string;address:string;is_rep:boolean;is_rep_plus:boolean;usual_distance_km:number|null;notes:string|null}
type Mission={id:string;title:string|null;start_date:string;end_date:string;status:string;establishment_id?:string|null;issr_establishments:{name:string}|null}
type View='dashboard'|'missions'|'indemnities'|'establishments'
type Props={userId:string;initialEntries:EntrySummary[];initialMissions:Mission[];initialEstablishments:Establishment[]}

export default function AppShell({userId,initialEntries,initialMissions,initialEstablishments}:Props){
 const supabase=useMemo(()=>createClient(),[])
 const [view,setView]=useState<View>('dashboard'),[missions,setMissions]=useState(initialMissions),[establishments,setEstablishments]=useState(initialEstablishments)
 const [name,setName]=useState(''),[address,setAddress]=useState(''),[rep,setRep]=useState(false),[repPlus,setRepPlus]=useState(false),[km,setKm]=useState('')
 const [estId,setEstId]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[title,setTitle]=useState(''),[message,setMessage]=useState('')
 const month=new Date().toISOString().slice(0,7),today=new Date().toISOString().slice(0,10)
 const monthEntries=initialEntries.filter(e=>e.travel_date.startsWith(month))
 const stats=monthEntries.reduce((a,e)=>({days:a.days+1,km:a.km+Number(e.distance_km),total:a.total+Number(e.total_amount),rep:a.rep+Number(e.rep_bonus)+Number(e.rep_plus_bonus)}),{days:0,km:0,total:0,rep:0})
 const nextMission=missions.filter(m=>m.end_date>=today&&m.status!=='cancelled').sort((a,b)=>a.start_date.localeCompare(b.start_date))[0]
 async function addEstablishment(){if(!name.trim()||!address.trim()){setMessage('Nom et adresse obligatoires.');return}const {data,error}=await supabase.from('issr_establishments').insert({user_id:userId,name:name.trim(),address:address.trim(),is_rep:rep,is_rep_plus:repPlus,usual_distance_km:km?Number(km):null}).select().single();if(error){setMessage(error.message);return}setEstablishments(v=>[...v,data as Establishment].sort((a,b)=>a.name.localeCompare(b.name)));setName('');setAddress('');setKm('');setRep(false);setRepPlus(false);setMessage('Établissement enregistré.')}
 async function addMission(){if(!estId||!start||!end){setMessage('Choisissez un établissement et une période.');return}if(end<start){setMessage('La date de fin doit être postérieure au début.');return}const {data,error}=await supabase.from('issr_missions').insert({user_id:userId,establishment_id:estId,title:title.trim()||null,start_date:start,end_date:end,status:start<=today&&end>=today?'active':'planned'}).select('id,title,start_date,end_date,status,establishment_id,issr_establishments(name)').single();if(error){setMessage(error.message);return}setMissions(v=>[...v,data as unknown as Mission]);setTitle('');setStart('');setEnd('');setMessage('Mission créée.')}
 async function removeEstablishment(id:string){const {error}=await supabase.from('issr_establishments').delete().eq('id',id);if(!error)setEstablishments(v=>v.filter(e=>e.id!==id))}
 async function removeMission(id:string){const {error}=await supabase.from('issr_missions').delete().eq('id',id);if(!error)setMissions(v=>v.filter(m=>m.id!==id))}
 if(view==='indemnities')return <><div className="product-nav"><button onClick={()=>setView('dashboard')}>← Tableau de bord</button><strong>Mon Remplacement</strong></div><IssrApp userId={userId}/></>
 const nav=<nav className="product-tabs"><button className={view==='dashboard'?'active':''} onClick={()=>setView('dashboard')}>Tableau de bord</button><button className={view==='missions'?'active':''} onClick={()=>setView('missions')}>Mes missions</button><button onClick={()=>setView('indemnities')}>Mes indemnités</button><button className={view==='establishments'?'active':''} onClick={()=>setView('establishments')}>Mes établissements</button><button disabled>Mes bilans</button></nav>
 if(view==='establishments')return <div className="product-shell"><header className="product-hero"><div><span className="product-kicker">Mon Remplacement</span><h1>Mes établissements</h1><p>Enregistrez vos lieux de remplacement pour éviter les saisies répétitives.</p></div></header>{nav}<main className="dashboard-main"><section className="dashboard-panel"><div className="panel-heading"><div><span className="eyebrow">Nouveau</span><h2>Ajouter un établissement</h2></div></div><div className="mr-form"><label>Nom<input value={name} onChange={e=>setName(e.target.value)} placeholder="École, collège, lycée…"/></label><label>Adresse<input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Adresse complète"/></label><label>Distance habituelle (km)<input type="number" min="0" step="0.1" value={km} onChange={e=>setKm(e.target.value)}/></label><div className="mr-checks"><label><input type="checkbox" checked={rep} onChange={e=>{setRep(e.target.checked);if(e.target.checked)setRepPlus(false)}}/> REP</label><label><input type="checkbox" checked={repPlus} onChange={e=>{setRepPlus(e.target.checked);if(e.target.checked)setRep(false)}}/> REP+</label></div><button className="btn btn-primary" onClick={addEstablishment}>Enregistrer</button></div>{message&&<p className="mr-message">{message}</p>}</section><section className="dashboard-panel"><h2>Établissements enregistrés</h2><div className="mr-list">{establishments.length?establishments.map(e=><article key={e.id}><div><strong>{e.name}</strong><span>{e.address}</span><small>{e.is_rep_plus?'REP+':e.is_rep?'REP':'Hors REP'}{e.usual_distance_km!=null?` · ${e.usual_distance_km} km`:''}</small></div><button className="btn btn-danger" onClick={()=>removeEstablishment(e.id)}>Supprimer</button></article>):<div className="empty-state">Aucun établissement enregistré.</div>}</div></section></main></div>
 if(view==='missions')return <div className="product-shell"><header className="product-hero"><div><span className="product-kicker">Mon Remplacement</span><h1>Mes missions</h1><p>Planifiez vos périodes de remplacement et rattachez-les à un établissement.</p></div></header>{nav}<main className="dashboard-main"><section className="dashboard-panel"><div className="panel-heading"><div><span className="eyebrow">Nouvelle</span><h2>Créer une mission</h2></div></div><div className="mr-form"><label>Établissement<select value={estId} onChange={e=>setEstId(e.target.value)}><option value="">Sélectionner…</option>{establishments.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>Libellé (facultatif)<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex : remplacement CM2"/></label><label>Du<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Au<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><button className="btn btn-primary" onClick={addMission} disabled={!establishments.length}>Créer la mission</button></div>{!establishments.length&&<p className="mr-message">Ajoutez d’abord un établissement.</p>}{message&&<p className="mr-message">{message}</p>}</section><section className="dashboard-panel"><h2>Missions enregistrées</h2><div className="mr-list">{missions.length?missions.sort((a,b)=>b.start_date.localeCompare(a.start_date)).map(m=><article key={m.id}><div><strong>{m.issr_establishments?.name??m.title??'Mission'}</strong><span>Du {new Date(m.start_date+'T12:00:00').toLocaleDateString('fr-FR')} au {new Date(m.end_date+'T12:00:00').toLocaleDateString('fr-FR')}</span><small>{m.status==='active'?'En cours':m.status==='completed'?'Terminée':'Planifiée'}</small></div><button className="btn btn-danger" onClick={()=>removeMission(m.id)}>Supprimer</button></article>):<div className="empty-state">Aucune mission enregistrée.</div>}</div></section></main></div>
 return <div className="product-shell"><header className="product-hero"><div><span className="product-kicker">Mon Remplacement</span><h1>Bonjour 👋</h1><p>Voici l’essentiel de votre activité pour ce mois.</p></div><button className="btn btn-primary" onClick={()=>setView('missions')}>+ Créer une mission</button></header>{nav}<main className="dashboard-main"><section className="dashboard-stats"><article><span>Jours déclarés</span><strong>{stats.days}</strong><small>ce mois</small></article><article><span>ISSR estimées</span><strong>{stats.total.toLocaleString('fr-FR',{style:'currency',currency:'EUR'})}</strong><small>indemnités + primes</small></article><article><span>Distance</span><strong>{stats.km.toLocaleString('fr-FR',{maximumFractionDigits:1})} km</strong><small>trajets enregistrés</small></article><article><span>REP / REP+</span><strong>{stats.rep.toLocaleString('fr-FR',{style:'currency',currency:'EUR'})}</strong><small>primes estimées</small></article></section><section className="dashboard-grid"><article className="dashboard-panel"><div className="panel-heading"><div><span className="eyebrow">À venir</span><h2>Prochaine mission</h2></div><span className="status-chip">Planning</span></div>{nextMission?<div className="next-mission"><strong>{nextMission.issr_establishments?.name??nextMission.title??'Mission'}</strong><span>Du {new Date(nextMission.start_date+'T12:00:00').toLocaleDateString('fr-FR')} au {new Date(nextMission.end_date+'T12:00:00').toLocaleDateString('fr-FR')}</span></div>:<div className="empty-state"><strong>Aucune mission planifiée</strong><p>Créez votre prochain remplacement en quelques secondes.</p></div>}</article><article className="dashboard-panel quick-panel"><div><span className="eyebrow">Accès rapide</span><h2>Que souhaitez-vous faire ?</h2></div><button onClick={()=>setView('indemnities')}><span>€</span><div><strong>Mes indemnités</strong><small>Calculer ou consulter les ISSR</small></div><b>→</b></button><button onClick={()=>setView('establishments')}><span>🏫</span><div><strong>Ajouter un établissement</strong><small>{establishments.length} enregistré(s)</small></div><b>→</b></button><button onClick={()=>setView('missions')}><span>📅</span><div><strong>Créer une mission</strong><small>Planifier un remplacement</small></div><b>→</b></button></article></section></main></div>
}