'use client'

import { useEffect, useMemo, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

type Doc={id:string;title:string;category:string;file_name:string;storage_path:string;mime_type:string;size_bytes:number;created_at:string;mission_id:string|null}
type Mission={id:string;title:string|null;start_date:string;issr_establishments:{name:string}|null}
const CATEGORIES=[['arrete','Arrêté / affectation'],['attestation','Attestation'],['emploi_du_temps','Emploi du temps'],['fiche_paie','Fiche de paie'],['justificatif','Justificatif'],['other','Autre']] as const
function categoryLabel(value:string){return CATEGORIES.find(([v])=>v===value)?.[1]??'Autre'}
function sizeLabel(bytes:number){if(bytes<1024*1024)return `${Math.max(1,Math.round(bytes/1024))} Ko`;return `${(bytes/1024/1024).toLocaleString('fr-FR',{maximumFractionDigits:1})} Mo`}

export default function DocumentsView({userId}:{userId:string}){
 const supabase=useMemo(()=>createClient(),[])
 const [docs,setDocs]=useState<Doc[]>([]),[missions,setMissions]=useState<Mission[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false)
 const [title,setTitle]=useState(''),[category,setCategory]=useState('arrete'),[missionId,setMissionId]=useState(''),[file,setFile]=useState<File|null>(null),[message,setMessage]=useState('')
 const [preview,setPreview]=useState<{doc:Doc;url:string}|null>(null)
 useEffect(()=>{let live=true;(async()=>{setLoading(true);const [d,m]=await Promise.all([supabase.from('issr_documents').select('*').order('created_at',{ascending:false}),supabase.from('issr_missions').select('id,title,start_date,issr_establishments(name)').order('start_date',{ascending:false})]);if(!live)return;setDocs((d.data??[]) as Doc[]);setMissions((m.data??[]) as unknown as Mission[]);setLoading(false)})();return()=>{live=false}},[supabase,userId])
 async function upload(){if(!file){setMessage('Choisissez un fichier.');return}if(!['application/pdf','image/jpeg','image/png','image/webp'].includes(file.type)){setMessage('Formats acceptés : PDF, JPG, PNG ou WebP.');return}if(file.size>10*1024*1024){setMessage('Le fichier ne doit pas dépasser 10 Mo.');return}setBusy(true);setMessage('');try{const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,'_'),path=`${userId}/${crypto.randomUUID()}-${safe}`;const {error:uploadError}=await supabase.storage.from('issr-documents').upload(path,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;const row={user_id:userId,mission_id:missionId||null,title:title.trim()||file.name.replace(/\.[^.]+$/,''),category,file_name:file.name,storage_path:path,mime_type:file.type,size_bytes:file.size};const {data,error}=await supabase.from('issr_documents').insert(row).select().single();if(error){await supabase.storage.from('issr-documents').remove([path]);throw error}setDocs(v=>[data as Doc,...v]);setTitle('');setMissionId('');setFile(null);const input=document.getElementById('document-file') as HTMLInputElement|null;if(input)input.value='';setMessage('Document ajouté.')}catch(e:any){setMessage(e?.message||'Impossible d’ajouter le document.')}finally{setBusy(false)}}
 async function consult(doc:Doc){setBusy(true);setMessage('');const {data,error}=await supabase.storage.from('issr-documents').createSignedUrl(doc.storage_path,300);setBusy(false);if(error||!data?.signedUrl){setMessage(error?.message||'Impossible d’ouvrir ce document.');return}setPreview({doc,url:data.signedUrl})}
 async function download(doc:Doc){setBusy(true);setMessage('');const {data,error}=await supabase.storage.from('issr-documents').download(doc.storage_path);setBusy(false);if(error||!data){setMessage(error?.message||'Impossible de télécharger ce document.');return}const url=URL.createObjectURL(data),a=document.createElement('a');a.href=url;a.download=doc.file_name;a.style.display='none';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1200)}
 async function remove(doc:Doc){setBusy(true);setMessage('');const {error:fileError}=await supabase.storage.from('issr-documents').remove([doc.storage_path]);if(fileError){setBusy(false);setMessage(fileError.message);return}const {error}=await supabase.from('issr_documents').delete().eq('id',doc.id);setBusy(false);if(error){setMessage(error.message);return}setDocs(v=>v.filter(d=>d.id!==doc.id));if(preview?.doc.id===doc.id)setPreview(null)}
 const grouped=useMemo(()=>CATEGORIES.map(([value,label])=>({value,label,docs:docs.filter(d=>d.category===value)})).filter(g=>g.docs.length),[docs])
 return <main className="dashboard-main documents-page">
  <section className="dashboard-panel document-upload"><div><span className="eyebrow">Classement</span><h2>Ajouter un document</h2><p>Conservez vos pièces utiles au même endroit. Les fichiers restent privés dans votre espace.</p></div><div className="document-form"><label>Titre<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex : arrêté de remplacement septembre"/></label><label>Type<select value={category} onChange={e=>setCategory(e.target.value)}>{CATEGORIES.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Mission associée<select value={missionId} onChange={e=>setMissionId(e.target.value)}><option value="">Aucune</option>{missions.map(m=><option key={m.id} value={m.id}>{m.issr_establishments?.name??m.title??'Mission'} · {new Date(`${m.start_date}T12:00:00`).toLocaleDateString('fr-FR')}</option>)}</select></label><label className="document-file">Fichier<input id="document-file" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]??null)}/><small>PDF, JPG, PNG ou WebP · 10 Mo maximum</small></label><button className="btn btn-primary" onClick={upload} disabled={busy||!file}>{busy?'Traitement…':'Ajouter le document'}</button></div>{message&&<p className="mr-message">{message}</p>}</section>
  <section className="dashboard-panel"><div className="document-list-head"><div><span className="eyebrow">Bibliothèque</span><h2>Mes documents</h2></div><span>{docs.length} fichier(s)</span></div>{loading?<div className="empty-state">Chargement des documents…</div>:!docs.length?<div className="empty-state"><strong>Aucun document enregistré</strong><p>Ajoutez votre premier arrêté, justificatif ou emploi du temps.</p></div>:<div className="document-groups">{grouped.map(group=><section key={group.value}><h3>{group.label}</h3><div className="document-list">{group.docs.map(doc=><article key={doc.id}><div className="document-file-badge">{doc.mime_type==='application/pdf'?'PDF':'IMG'}</div><div className="document-meta"><strong>{doc.title}</strong><span>{doc.file_name}</span><small>{sizeLabel(doc.size_bytes)} · ajouté le {new Date(doc.created_at).toLocaleDateString('fr-FR')}</small></div><div className="document-actions"><button className="btn btn-export" onClick={()=>consult(doc)} disabled={busy}>Consulter</button><button className="btn btn-export" onClick={()=>download(doc)} disabled={busy}>Télécharger</button><button className="btn btn-danger" onClick={()=>remove(doc)} disabled={busy}>Supprimer</button></div></article>)}</div></section>)}</div>}</section>
  {preview&&<div className="document-preview-backdrop" role="dialog" aria-modal="true" aria-label={`Consultation de ${preview.doc.title}`}><div className="document-preview"><header><div><strong>{preview.doc.title}</strong><small>{categoryLabel(preview.doc.category)}</small></div><button className="document-preview-close" onClick={()=>setPreview(null)} aria-label="Fermer la consultation">×</button></header><div className="document-preview-body">{preview.doc.mime_type==='application/pdf'?<iframe title={preview.doc.title} src={preview.url}/>:<img src={preview.url} alt={preview.doc.title}/>}</div><footer><button className="btn btn-export" onClick={()=>download(preview.doc)}>Télécharger</button></footer></div></div>}
 </main>
}
